[package]
name = "hello-bevy"
version = "0.1.0"
authors = ["Jon Allen <jon@ylixir.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
